MvcProjeKampi/Controllers/SkillAreaController.cs
using Business.Concrete;
using DataAccess.EntityFramework;
using Entity.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace MvcProjeKampi.Controllers
{
    public class SkillAreaController : Controller
    {
        SkillAreaManager skillAreaManager = new SkillAreaManager(new EfSkillAreaDal());
        public ActionResult Index(int? page)
        {
            var skillvalues = skillAreaManager.GetList().ToPagedList(page ?? 1, 4);
            return View(skillvalues);
        }
        [HttpGet]
        public ActionResult AddSkillArea()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddSkillArea(SkillArea skill)
        {
            skillAreaManager.SkillAreaAdd(skill);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult UpdateSkillArea(int id)
        {
            var value = skillAreaManager.GetByIdSkillArea(id);
            return View(value);
        }
        [HttpPost]
        public ActionResult UpdateSkillArea(SkillArea skill)
        {
            skillAreaManager.SkillAreaUpdate(skill);
            return RedirectToAction("Index");
        }
        public ActionResult DeleteSkillArea(int Id)
        {
            var talentValues = skillAreaManager.GetByIdSkillArea(Id);
            skillAreaManager.SkillAreaDelete(talentValues);
            return RedirectToAction("Index");
        }


    }
}

MvcProjeKampi/Views/SkillArea/AddSkillArea.cshtml
@model Entity.Concrete.SkillArea
@{
    ViewBag.Title = "AddSkillArea";
    Layout = "~/Views/Shared/_TalentLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <title>Yetenek Bölümü Ekleme</title>
</head>
<body>
    @using (Html.BeginForm("AddSkillArea", "SkillArea", FormMethod.Post))
    {
        <form method="post" action="AddSkillArea">

            @Html.Label("Yetenek Bölümü Adı")
            <br />
            @Html.TextBoxFor(x => x.Area, new { @class = "forn-control" })
            <br /> <br />
            @Html.Label("Yetenek Bölümü Detayı")
            @Html.TextAreaFor(x => x.AreaDetails, new { @class = "form-control" })
            <br /> <br />
            <button type="submit" class="btn btn-primary">Kaydet</button>
            <br />
        </form>
    }
    <!--bar-js-->
    <script src="~/AdminLTE-3.0.4/skills/js/bars.js"></script>
    <p>
    </p>
</body>
</html>

MvcProjeKampi/Views/SkillArea/Index.cshtml
@using Entity.Concrete
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<SkillArea>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_TalentLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <title>Yetenek Bölümü</title>
</head>
<body>
        <h1>Yetenek Alanı Sayfası</h1>
        <a href="/SkillArea/AddSkillArea/" class="btn btn-info">Yeni Yetenek Alanı Ekle</a>
        <!-- main-row-one -->
        <div style="margin-right: 1em; margin-left: 1em">
            <br />
            <table class="table table-bordered" style="color: azure">
                <tr>
                    <th style="width: 1%; text-align: center"><b>#</b></th>
                    <th style="width: 10%; text-align: center"><b>Yetenek Alanı</b></th>
                    <th style="width: 15%; text-align: center"><b>Yetenek Alanı Detayı</b></th>
                    <th style="width: 1%; text-align: center"><b>Sil</b></th>
                    <th style="width: 1%; text-align: center"><b>Güncelle</b></th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <th style="width: 1%; text-align: center"><b>@item.SkillAreaId</b></th>
                        <td style="width: 10%; text-align: center"><b>@item.Area</b></td>
                        <td style="width: 15%; text-align: center"><b>@item.AreaDetails</b></td>
                        <td style="width: 1%; text-align: center"><a href="/SkillArea/DeleteSkillArea/@item.SkillAreaId" class="btn btn-danger">Sil</a></td>
                        <td><a href="/SkillArea/UpdateSkillArea/@item.SkillAreaId" class="btn btn-warning">Güncelle</a></td>
                    </tr>
                }
            </table>
            <div style="color: beige">
                <ul class="alert-light" style="font-size: 20px"> @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))</ul>
            </div>
        </div>
        <script src="~/AdminLTE-3.0.4/skills/js/bars.js"></script>
</body>
</html>

MvcProjeKampi/Views/SkillArea/UpdateSkillArea.cshtml
@model  Entity.Concrete.SkillArea
@{
    ViewBag.Title = "UpdateSkillArea";
    Layout = "~/Views/Shared/_TalentLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <title>Yetenek Alanı Güncelleme</title>
</head>
<body>
    <h3 class="title">Yetenek Alanı Güncelle</h3>
    <div class="col-md-6 skills-right bar_group">
        @using (Html.BeginForm("UpdateSkillArea", "SkillArea", FormMethod.Post))
        {
            <form method="post" action="#">
                <div class="modal-body">
                    @Html.HiddenFor(x => x.SkillAreaId, new { @class = "form-control" })
                    @Html.Label("Yetenek Alanı Adı")
                    <br />
                    @Html.TextBoxFor(x => x.Area, new { @class = "form-control" })
                    <br />
                    @Html.Label("Yetenek Alanı Detayı")
                    <br />
                    @Html.TextAreaFor(x => x.AreaDetails, new { @class = "form-control" })
                    <br /> 
                    <button class="btn btn-primary">Kaydet</button>
                </div>
            </form>
        }
    </div>
    <script src="~/AdminLTE-3.0.4/skills/js/bars.js"></script>
    <div class="clear"> </div>
</body>
</html>